#!/usr/bin/env python3
"""
Verification script for the ShowResponse model_info issue #607.
Tests both the missing model_info scenario (cloud models) and normal scenario with model_info.
"""

import sys
from pydantic import ValidationError
from ollama._types import ShowResponse

def test_missing_model_info():
    """Test payload without model_info key (cloud models scenario)."""
    payload_without_model_info = {
        'modelfile': '# Modelfile generated by "ollama show"...',
        'template': '{{ .Prompt }}',
        'details': {
            'parent_model': '', 
            'format': '', 
            'family': '', 
            'families': None, 
            'parameter_size': '', 
            'quantization_level': ''
        },
        'capabilities': ['completion', 'tools', 'thinking'],
        'modified_at': '2025-12-24T10:08:53.438277171-05:00',
    }
    
    try:
        result = ShowResponse.model_validate(payload_without_model_info)
        print("✓ PASS: Missing model_info payload validated successfully")
        print(f"  result.modelinfo = {result.modelinfo}")
        return True
    except ValidationError as e:
        print("✗ FAIL: Missing model_info payload caused ValidationError")
        print(f"  Error: {e}")
        return False

def test_with_model_info():
    """Test payload with model_info key (normal scenario)."""
    payload_with_model_info = {
        'modelfile': '# Modelfile generated by "ollama show"...',
        'template': '{{ .Prompt }}',
        'details': {
            'parent_model': '', 
            'format': '', 
            'family': '', 
            'families': None, 
            'parameter_size': '', 
            'quantization_level': ''
        },
        'capabilities': ['completion', 'tools', 'thinking'],
        'modified_at': '2025-12-24T10:08:53.438277171-05:00',
        'model_info': {'general.architecture': 'llama'},
    }
    
    try:
        result = ShowResponse.model_validate(payload_with_model_info)
        expected_model_info = {'general.architecture': 'llama'}
        if result.modelinfo == expected_model_info:
            print("✓ PASS: With model_info payload validated and populated correctly")
            print(f"  result.modelinfo = {result.modelinfo}")
            return True
        else:
            print("✗ FAIL: With model_info payload validated but modelinfo incorrect")
            print(f"  Expected: {expected_model_info}")
            print(f"  Actual: {result.modelinfo}")
            return False
    except ValidationError as e:
        print("✗ FAIL: With model_info payload caused ValidationError")
        print(f"  Error: {e}")
        return False

def main():
    print("=== Testing ShowResponse model_info handling ===")
    print()
    
    # Test missing model_info (the bug scenario)
    missing_passed = test_missing_model_info()
    print()
    
    # Test with model_info (positive control)
    with_passed = test_with_model_info()
    print()
    
    # Determine if current state is as expected
    if missing_passed and with_passed:
        print("=== CURRENT STATE: FIXED ===")
        print("Both tests passed - model_info is properly optional")
        return 0
    elif not missing_passed and with_passed:
        print("=== CURRENT STATE: BUGGY ===") 
        print("Missing model_info fails (expected for unfixed code)")
        return 0
    else:
        print("=== CURRENT STATE: UNEXPECTED ===")
        print("Test results don't match expected patterns")
        return 1

if __name__ == "__main__":
    sys.exit(main())